"""Initial migration

Revision ID: b61d5ce8eb84
Revises: 
Create Date: 2024-11-24 14:08:22.096054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b61d5ce8eb84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('charge_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'webhook_received')
    op.drop_column('transactions', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('webhook_received', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'charge_id')
    # ### end Alembic commands ###
